#!/usr/bin/env bash
rst2html5 --jquery --reveal-js --reveal-js-opts theme=pdf,themepath=~/Src/presentations/printtopdf --pygments pbdtt_04sep.rst > output/reveal.html
sed -i '' "s/&#39;/'/g; s/&lt;/</g; s/&gt;/>/g; s/&amp;/\&/g;" output/reveal.html
